const data = [
  {
    first_name: "Test",
    last_name: "Test",
    middle_name: "Test",
    address: "Apt 1835",
    contact: "622-545-6385",
    gender: "F",
    suffix: "Jr",
    birth_date: "12/14/2024",
    email: "sdevinn0@nbcnews.com",
  },
  {
    first_name: "Employee",
    last_name: "Employee",
    middle_name: "Cindy",
    address: "Apt 699",
    contact: "901-639-4953",
    gender: "F",
    suffix: "III",
    birth_date: "11/23/2024",
    email: "cbusek1@geocities.com",
  },
  {
    first_name: "Kaitlyn",
    last_name: "Constantinou",
    middle_name: "Glynis",
    address: "Suite 87",
    contact: "725-486-9839",
    gender: "F",
    suffix: "II",
    birth_date: "9/4/2025",
    email: "gconstantinou2@sohu.com",
  },
  {
    first_name: "Joyce",
    last_name: "Asmus",
    middle_name: "Alicea",
    address: "PO Box 74021",
    contact: "351-216-9106",
    gender: "F",
    suffix: "II",
    birth_date: "11/24/2024",
    email: "aasmus3@ezinearticles.com",
  },
  {
    first_name: "Ogdan",
    last_name: "Iacopini",
    middle_name: "Ruprecht",
    address: "20th Floor",
    contact: "568-276-3198",
    gender: "M",
    suffix: "Sr",
    birth_date: "7/30/2025",
    email: "riacopini4@dmoz.org",
  },
  {
    first_name: "Verla",
    last_name: "Schnitter",
    middle_name: "Leticia",
    address: "PO Box 51867",
    contact: "760-398-4560",
    gender: "F",
    suffix: "III",
    birth_date: "11/22/2024",
    email: "lschnitter5@macromedia.com",
  },
  {
    first_name: "Jerry",
    last_name: "Crielly",
    middle_name: "Glynnis",
    address: "Suite 5",
    contact: "794-785-0649",
    gender: "F",
    suffix: "Sr",
    birth_date: "8/15/2025",
    email: "gcrielly6@ibm.com",
  },
  {
    first_name: "Bella",
    last_name: "Sysland",
    middle_name: "Florry",
    address: "Apt 1634",
    contact: "176-691-9083",
    gender: "F",
    suffix: "III",
    birth_date: "4/20/2025",
    email: "fsysland7@csmonitor.com",
  },
  {
    first_name: "Tildie",
    last_name: "Gulc",
    middle_name: "Milzie",
    address: "Apt 803",
    contact: "134-969-9690",
    gender: "F",
    suffix: "Sr",
    birth_date: "1/2/2025",
    email: "mgulc8@e-recht24.de",
  },
  {
    first_name: "Adaline",
    last_name: "Tym",
    middle_name: "Ondrea",
    address: "Room 216",
    contact: "415-480-1521",
    gender: "F",
    suffix: "III",
    birth_date: "4/9/2025",
    email: "otym9@godaddy.com",
  },
];
module.exports = data;
